/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CatalogoRouteImport } from './routes/catalogo'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PainelProdutosRouteImport } from './routes/painel.produtos'
import { Route as CatalogoProductIdRouteImport } from './routes/catalogo.$productId'

const CatalogoRoute = CatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelProdutosRoute = PainelProdutosRouteImport.update({
  id: '/painel/produtos',
  path: '/painel/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoProductIdRoute = CatalogoProductIdRouteImport.update({
  id: '/$productId',
  path: '/$productId',
  getParentRoute: () => CatalogoRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/catalogo': typeof CatalogoRouteWithChildren
  '/catalogo/$productId': typeof CatalogoProductIdRoute
  '/painel/produtos': typeof PainelProdutosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/catalogo': typeof CatalogoRouteWithChildren
  '/catalogo/$productId': typeof CatalogoProductIdRoute
  '/painel/produtos': typeof PainelProdutosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/catalogo': typeof CatalogoRouteWithChildren
  '/catalogo/$productId': typeof CatalogoProductIdRoute
  '/painel/produtos': typeof PainelProdutosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/catalogo' | '/catalogo/$productId' | '/painel/produtos'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/catalogo' | '/catalogo/$productId' | '/painel/produtos'
  id:
    | '__root__'
    | '/'
    | '/catalogo'
    | '/catalogo/$productId'
    | '/painel/produtos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CatalogoRoute: typeof CatalogoRouteWithChildren
  PainelProdutosRoute: typeof PainelProdutosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/catalogo': {
      id: '/catalogo'
      path: '/catalogo'
      fullPath: '/catalogo'
      preLoaderRoute: typeof CatalogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel/produtos': {
      id: '/painel/produtos'
      path: '/painel/produtos'
      fullPath: '/painel/produtos'
      preLoaderRoute: typeof PainelProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo/$productId': {
      id: '/catalogo/$productId'
      path: '/$productId'
      fullPath: '/catalogo/$productId'
      preLoaderRoute: typeof CatalogoProductIdRouteImport
      parentRoute: typeof CatalogoRoute
    }
  }
}

interface CatalogoRouteChildren {
  CatalogoProductIdRoute: typeof CatalogoProductIdRoute
}

const CatalogoRouteChildren: CatalogoRouteChildren = {
  CatalogoProductIdRoute: CatalogoProductIdRoute,
}

const CatalogoRouteWithChildren = CatalogoRoute._addFileChildren(
  CatalogoRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CatalogoRoute: CatalogoRouteWithChildren,
  PainelProdutosRoute: PainelProdutosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
