/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatusAcessoRouteImport } from './routes/status-acesso'
import { Route as EntregaRouteImport } from './routes/entrega'
import { Route as CatalogoRouteImport } from './routes/catalogo'
import { Route as BemVindoRouteImport } from './routes/bem-vindo'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AcessoRouteImport } from './routes/acesso'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CatalogoProductIdRouteImport } from './routes/catalogo.$productId'
import { Route as AuthenticatedPainelProdutosRouteImport } from './routes/_authenticated/painel.produtos'
import { Route as ApiPublicHotmartWebhookRouteImport } from './routes/api/public/hotmart/webhook'

const StatusAcessoRoute = StatusAcessoRouteImport.update({
  id: '/status-acesso',
  path: '/status-acesso',
  getParentRoute: () => rootRouteImport,
} as any)
const EntregaRoute = EntregaRouteImport.update({
  id: '/entrega',
  path: '/entrega',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoRoute = CatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => rootRouteImport,
} as any)
const BemVindoRoute = BemVindoRouteImport.update({
  id: '/bem-vindo',
  path: '/bem-vindo',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AcessoRoute = AcessoRouteImport.update({
  id: '/acesso',
  path: '/acesso',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoProductIdRoute = CatalogoProductIdRouteImport.update({
  id: '/$productId',
  path: '/$productId',
  getParentRoute: () => CatalogoRoute,
} as any)
const AuthenticatedPainelProdutosRoute =
  AuthenticatedPainelProdutosRouteImport.update({
    id: '/painel/produtos',
    path: '/painel/produtos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicHotmartWebhookRoute = ApiPublicHotmartWebhookRouteImport.update({
  id: '/api/public/hotmart/webhook',
  path: '/api/public/hotmart/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acesso': typeof AcessoRoute
  '/auth': typeof AuthRoute
  '/bem-vindo': typeof BemVindoRoute
  '/catalogo': typeof CatalogoRouteWithChildren
  '/entrega': typeof EntregaRoute
  '/status-acesso': typeof StatusAcessoRoute
  '/catalogo/$productId': typeof CatalogoProductIdRoute
  '/painel/produtos': typeof AuthenticatedPainelProdutosRoute
  '/api/public/hotmart/webhook': typeof ApiPublicHotmartWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acesso': typeof AcessoRoute
  '/auth': typeof AuthRoute
  '/bem-vindo': typeof BemVindoRoute
  '/catalogo': typeof CatalogoRouteWithChildren
  '/entrega': typeof EntregaRoute
  '/status-acesso': typeof StatusAcessoRoute
  '/catalogo/$productId': typeof CatalogoProductIdRoute
  '/painel/produtos': typeof AuthenticatedPainelProdutosRoute
  '/api/public/hotmart/webhook': typeof ApiPublicHotmartWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/acesso': typeof AcessoRoute
  '/auth': typeof AuthRoute
  '/bem-vindo': typeof BemVindoRoute
  '/catalogo': typeof CatalogoRouteWithChildren
  '/entrega': typeof EntregaRoute
  '/status-acesso': typeof StatusAcessoRoute
  '/catalogo/$productId': typeof CatalogoProductIdRoute
  '/_authenticated/painel/produtos': typeof AuthenticatedPainelProdutosRoute
  '/api/public/hotmart/webhook': typeof ApiPublicHotmartWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acesso'
    | '/auth'
    | '/bem-vindo'
    | '/catalogo'
    | '/entrega'
    | '/status-acesso'
    | '/catalogo/$productId'
    | '/painel/produtos'
    | '/api/public/hotmart/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acesso'
    | '/auth'
    | '/bem-vindo'
    | '/catalogo'
    | '/entrega'
    | '/status-acesso'
    | '/catalogo/$productId'
    | '/painel/produtos'
    | '/api/public/hotmart/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/acesso'
    | '/auth'
    | '/bem-vindo'
    | '/catalogo'
    | '/entrega'
    | '/status-acesso'
    | '/catalogo/$productId'
    | '/_authenticated/painel/produtos'
    | '/api/public/hotmart/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AcessoRoute: typeof AcessoRoute
  AuthRoute: typeof AuthRoute
  BemVindoRoute: typeof BemVindoRoute
  CatalogoRoute: typeof CatalogoRouteWithChildren
  EntregaRoute: typeof EntregaRoute
  StatusAcessoRoute: typeof StatusAcessoRoute
  ApiPublicHotmartWebhookRoute: typeof ApiPublicHotmartWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/status-acesso': {
      id: '/status-acesso'
      path: '/status-acesso'
      fullPath: '/status-acesso'
      preLoaderRoute: typeof StatusAcessoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrega': {
      id: '/entrega'
      path: '/entrega'
      fullPath: '/entrega'
      preLoaderRoute: typeof EntregaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo': {
      id: '/catalogo'
      path: '/catalogo'
      fullPath: '/catalogo'
      preLoaderRoute: typeof CatalogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bem-vindo': {
      id: '/bem-vindo'
      path: '/bem-vindo'
      fullPath: '/bem-vindo'
      preLoaderRoute: typeof BemVindoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acesso': {
      id: '/acesso'
      path: '/acesso'
      fullPath: '/acesso'
      preLoaderRoute: typeof AcessoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo/$productId': {
      id: '/catalogo/$productId'
      path: '/$productId'
      fullPath: '/catalogo/$productId'
      preLoaderRoute: typeof CatalogoProductIdRouteImport
      parentRoute: typeof CatalogoRoute
    }
    '/_authenticated/painel/produtos': {
      id: '/_authenticated/painel/produtos'
      path: '/painel/produtos'
      fullPath: '/painel/produtos'
      preLoaderRoute: typeof AuthenticatedPainelProdutosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/hotmart/webhook': {
      id: '/api/public/hotmart/webhook'
      path: '/api/public/hotmart/webhook'
      fullPath: '/api/public/hotmart/webhook'
      preLoaderRoute: typeof ApiPublicHotmartWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedPainelProdutosRoute: typeof AuthenticatedPainelProdutosRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedPainelProdutosRoute: AuthenticatedPainelProdutosRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface CatalogoRouteChildren {
  CatalogoProductIdRoute: typeof CatalogoProductIdRoute
}

const CatalogoRouteChildren: CatalogoRouteChildren = {
  CatalogoProductIdRoute: CatalogoProductIdRoute,
}

const CatalogoRouteWithChildren = CatalogoRoute._addFileChildren(
  CatalogoRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AcessoRoute: AcessoRoute,
  AuthRoute: AuthRoute,
  BemVindoRoute: BemVindoRoute,
  CatalogoRoute: CatalogoRouteWithChildren,
  EntregaRoute: EntregaRoute,
  StatusAcessoRoute: StatusAcessoRoute,
  ApiPublicHotmartWebhookRoute: ApiPublicHotmartWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
